"""administrative_financial_mvp"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id"),
    )
    op.create_index(
        op.f("ix_patients_organization_id"), "patients", ["organization_id"], unique=False
    )
    op.create_table(
        "professionals",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id"),
        sa.UniqueConstraint("organization_id", "user_id"),
    )
    op.create_index(
        op.f("ix_professionals_organization_id"), "professionals", ["organization_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_price_cents", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("default_price_cents >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id"),
    )
    op.create_index(
        op.f("ix_services_organization_id"), "services", ["organization_id"], unique=False
    )
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("professional_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column("starts_at", sa.BigInteger(), nullable=False),
        sa.Column("ends_at", sa.BigInteger(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("status IN ('SCHEDULED','COMPLETED','CANCELED')"),
        sa.CheckConstraint("ends_at > starts_at"),
        sa.CheckConstraint("price_cents >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id", "patient_id"],
            ["patients.organization_id", "patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "professional_id"],
            ["professionals.organization_id", "professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "service_id"],
            ["services.organization_id", "services.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id"),
    )
    op.create_index(
        op.f("ix_appointments_organization_id"), "appointments", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_professional_id"), "appointments", ["professional_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_starts_at"), "appointments", ["starts_at"], unique=False)
    op.create_table(
        "attendances",
        sa.Column("appointment_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("professional_id", sa.String(length=36), nullable=False),
        sa.Column("service_name", sa.String(length=120), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("price_cents >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id", "appointment_id"],
            ["appointments.organization_id", "appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "patient_id"],
            ["patients.organization_id", "patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "professional_id"],
            ["professionals.organization_id", "professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "appointment_id"),
        sa.UniqueConstraint("organization_id", "id"),
    )
    op.create_index(
        op.f("ix_attendances_occurred_at"), "attendances", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_attendances_organization_id"), "attendances", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_attendances_patient_id"), "attendances", ["patient_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("attendance_id", sa.String(length=36), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("received_at", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("method IN ('PIX','CASH','CARD','TRANSFER')"),
        sa.CheckConstraint("amount_cents > 0"),
        sa.ForeignKeyConstraint(
            ["organization_id", "attendance_id"],
            ["attendances.organization_id", "attendances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_payments_attendance_id"), "payments", ["attendance_id"], unique=False)
    op.create_index(
        op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_payments_received_at"), "payments", ["received_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_received_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_attendance_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_attendances_patient_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_organization_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_occurred_at"), table_name="attendances")
    op.drop_table("attendances")
    op.drop_index(op.f("ix_appointments_starts_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_professional_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_organization_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_services_organization_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_professionals_organization_id"), table_name="professionals")
    op.drop_table("professionals")
    op.drop_index(op.f("ix_patients_organization_id"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
